Module2 task1
htmlacademy-vue/1310789-pizza-1 pull request #3
Opened 2021-07-12 18:43 UTC by vovaborisenko

2021-07-12 19:38 UTC, Djaler requested changes
Совсем мелочь, но всё же. В задании указано 
`Создайте общие компоненты в директории frontend/src/common/components`

2021-07-12 19:38 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +            v-model="filling.count"
тут неявно мутируются данные, переданные через проп. так делать не стоит, нужно данные явно передавать наверх с помощью событий

2021-07-12 19:38 UTC, Djaler commented on src/frontend/src/components/SelectorItem.vue
> +      default: "tomatoes",
мне кажется, тут дефолтное значение не особо имеет смысл

2021-07-12 19:38 UTC, Djaler commented on src/frontend/src/layouts/AppLayout.vue
> +    <Index />
в задании сказано подключать layout в index, а не наоборот

2021-07-17 10:06 UTC, vovaborisenko commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +            v-model="filling.count"
исправил

2021-07-17 10:06 UTC, vovaborisenko commented on src/frontend/src/components/SelectorItem.vue
> +      default: "tomatoes",
убрал

2021-07-17 10:06 UTC, vovaborisenko commented on src/frontend/src/layouts/AppLayout.vue
> +    <Index />
исправил

2021-07-17 13:29 UTC, merged